import { Inter } from "next/font/google";

import PrelineScript from '../components/PrelineScript'
import "./globals.css";
import Navbar from "@/components/Navbar"
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <Navbar/>  <div> <Toaster position="top-right" reverseOrder={false}/> </div> 
      <PrelineScript/>{children} </body>
    </html>
  );
}
